name: flutter_map
description: A Dart implementation of Leaflet to provide a Map widget for Flutter apps
version: 0.13.1
repository: https://github.com/fleaflet/flutter_map

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  async: ^2.8.1
  collection: ^1.17.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  meta: ^1.3.0
  positioned_tap_detector_2: ^1.0.0
  proj4dart: ^2.0.0
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  location: ^4.1.1
  mockito: ^5.0.2
  pedantic: ^1.11.0
